### ISSUE TITLE
Automatically create PRs on client repositories when master is updated

### ISSUE THREAD

**Issue by alexandremeunier** [algolia/algoliasearch-client-readme-generator#37]
The current way of updating all READMEs is very cumbersome.

When the master branch changes, we could use TravisCI to automatically generate PRs on all the client repositories, with the updated READMEs. 

It would then be up to each client owner to merge the PR.

**Comment by vvo** [comment]
Ways:
- generate a specific client-readme-bot
- since all API clients are public, no need for him to have access to our repositories in write mode
- use http://nodegh.io/ and do `gh pr submit --algolia --branch master`

**Comment by redox** [comment]
Well done @CBaptiste 👍

**Comment by proudlygeek** [comment]
Awesome @CBaptiste 💯 , closed with PR #39
