### ISSUE TITLE
PR's content could list the commits that have been done

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-readme-generator#44]
Would be awesome if we could list the commits resulting in the diff of each PR.

 - I commit twice in the readme-generator
   - commit_message_1
   - commit_message_2
 - I want the resulting PRs to let me know about commit_message_1 + commit_message_2

**Comment by CBaptiste** [comment]
It should be working now.
Little note: when the folder template/ is being update, it is not possible to know which language it is impacting, therefore you can get more commits than you are supposed to have
example : https://github.com/algolia/algoliasearch-client-js/pull/230 (the swift and android ones)
