### ISSUE TITLE
Decentralize the documentation of each language.

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-client-readme-generator#46]
It would be nice if the tool could actually go get the snippets of every language directly in the corresponding language repositories.

Then if we make a PR adding some features, the bot could automatically add a commit to it with the updated README regarding the local snippets of the repository.

What do you think? I don't know how complex this would be to implement though.

**Comment by CBaptiste** [comment]
I am not sure I understand. You want the bot to detect directly what has been updated, update/add snippets and generate the readmes on the fly ?

**Comment by rayrutjes** [comment]
According to our discussion, given that the Layout is shared between the languages, my suggestion is not interesting at the moment, I'll close it for now.
