### ISSUE TITLE
remove linebreak and empty line detection when git add

### ISSUE THREAD

**Issue by CBaptiste** [algolia/algoliasearch-client-readme-generator#54]

**Comment by CBaptiste** [comment]
Hello @redox, I don't think it is possible to avoid the linebreak detection. A line break is adding a line, and   therefore it is a core git mechanism (detecting line removal and addition)
The only work that can be done to avoid that is actually no to generate the extra line, on ruby side

**Comment by redox** [comment]
Don't worry, I think we can live with it like that. In `ERB` you can ensure you don't add such newlines with `-%>` instead of `%>` -> let's say it's the responsibility of the developer to take care of that.

**Comment by CBaptiste** [comment]
Ok !
