### ISSUE TITLE
use [ci skip]

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-client-readme-generator#79]
To skip a build, it must have [ci skip] in the commit message.

We currently have "[ci-skip]" in the commit subject

Can we:
- have docs(README): automatic update as a commit message subject (first line)
- have [ci skip] in the body, at the end

This would avoid triggering builds, thx

https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build

**Comment by CBaptiste** [comment]
Argh sorry, I thought this was done already, I am on it

**Comment by CBaptiste** [comment]
done
